CREATE TABLE IF NOT EXISTS candidates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name_ru VARCHAR(255) NOT NULL,
    name_en VARCHAR(255) NOT NULL,
    resume_file_name VARCHAR(255),
    resume_file_url TEXT,
    interview_file TEXT,
    vacancy VARCHAR(255) NOT NULL,
    tech_stack TEXT,
    status VARCHAR(50) DEFAULT 'new',
    status_comment TEXT,
    screening_date TIMESTAMP WITH TIME ZONE,
    recruiter VARCHAR(255),
    telegram VARCHAR(255),
    status_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    location_city_country VARCHAR(255),
    english_level VARCHAR(50),
    min_salary INTEGER,
    max_salary INTEGER,
    salary_currency VARCHAR(3) DEFAULT 'USD',
    skype VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50),
    comments TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 