CREATE TABLE IF NOT EXISTS interviews (
    id SERIAL PRIMARY KEY,
    candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    screening_motivation TEXT,
    screening_expected_salary TEXT,
    screening_notice_time TEXT,
    screening_work_format TEXT,
    screening_english_level TEXT,
    screening_comments TEXT,
    technical_experience TEXT,
    technical_main_technologies TEXT,
    technical_coding_task TEXT,
    technical_algorithm_task TEXT,
    technical_system_design TEXT,
    technical_comments TEXT,
    final_team_work TEXT,
    final_problem_solving TEXT,
    final_communication TEXT,
    final_career_goals TEXT,
    final_comments TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(candidate_id)
); 